server.port=8082

spring.cloud.gateway.routes[0].id=cms
spring.cloud.gateway.routes[0].uri=http://localhost:8080
spring.cloud.gateway.routes[0].predicates[0]=Path=/mushroomPickers/**

spring.cloud.gateway.routes[1].id=ems-mushrooms
spring.cloud.gateway.routes[1].uri=http://localhost:8081
spring.cloud.gateway.routes[1].predicates[0]=Path=/mushrooms/**

spring.cloud.gateway.routes[2].id=ems-categories
spring.cloud.gateway.routes[2].uri=http://localhost:8081
spring.cloud.gateway.routes[2].predicates[0]=Path=/categories/**
